### ISSUE TITLE
apt module no longer supports 'installed' as a value for the 'state' property

### ISSUE THREAD

**Issue by pward123** [ANXS/hostname#19]
Getting the following error when running anxs.hostname under ansible 2.9.2
```
TASK [anxs.hostname : Hostname | Ensure dbus installed] *****************************************************************************
Sunday 15 December 2019  14:22:15 +0000 (0:00:01.512)       0:00:37.292 *******
fatal: [cloud1.savicontrols.local]: FAILED! => {"changed": false, "msg": "value of state must be one of: absent, build-dep, fixed, latest, present, got: installed"}
```

Also the same issue for the `Hostname | Install MDNS Components` step

**Comment by pward123** [comment]
Looks like this has already been resolved in the repo. Can we get a push to galaxy?

**Comment by attenzione** [comment]
Please bump the version and push to the galaxy ;)

**Comment by kevindurb** [comment]
Bump could you push the fix to galaxy please?

**Comment by otakup0pe** [comment]
well i finally remembered and then after stumbling into [this[(https://github.com/ansible/galaxy/issues/2362) a few times seem to have gotten it imported, `v2.1.1` should be up on galaxy.

apologies for it taking a while; life has a tendency to get in the way sometimes. if anyone wants to ride some metaphorical bikes with me and help maintain this (or other ANXS roles), hit me up in a new github issue.

**Comment by otakup0pe** [comment]
![slo fade](https://media.giphy.com/media/3og0IxWFUcSwKOD6fu/giphy.gif)
